[
      "import { SQSClient, ReceiveMessageCommand, DeleteMessageCommand } from '@aws-sdk/client-sqs';",
      "import pg from 'pg';",
      'const sqs = new SQSClient({});',
      'const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });',
      'async function pollQueue() {',
      '  const result = await sqs.send(new ReceiveMessageCommand({ QueueUrl: process.env.ORDERS_QUEUE_URL }));',
      '  for (const message of result.Messages ?? []) {',
      "    await pool.query('INSERT INTO orders (payload) VALUES ($1)', [message.Body]);",
      '    await sqs.send(new DeleteMessageCommand({ QueueUrl: process.env.ORDERS_QUEUE_URL, ReceiptHandle: message.ReceiptHandle }));',
      '  }',
      '}',
      'async function pollDlq() {',
      '  await sqs.send(new ReceiveMessageCommand({ QueueUrl: process.env.ORDERS_DLQ_URL }));',
      '}',
      'pollQueue();',
      'pollDlq();',
      '',
    ].join('\n')